#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>


red="\033[31m"
green="\033[32m"
yellow="\033[33m"
white="\033[0m"

dir_file="/usr/share/jd_openwrt_script"

start() {
	if [ ! -f $dir_file/JD_Script/jd.sh ];then
		clear
		echo "-------------------------------------------"
		echo -e "$green	    jd_openwrt_script$white"
		echo "-------------------------------------------"
		echo -e "$yellow 本插件使用到的脚本$white"
		echo "  1.https://github.com/xdhgsq/xdh.git"
		echo "  2.https://github.com/xdhgsq/xdh_plug.git"
		echo "  3.https://github.com/xdhgsq/Checkjs.git"
		echo ""
		echo -e "$yellow 等安装完成以后可以用以下代码调用脚本$white"
		echo -e "$green  sh \$jd $white      #调用JD_Script"
		echo -e "$green  sh \$jd wskey $white      #调用wskey转换"
		echo -e "$green  sh \$jd checkjs $white      #调用checkjs监控上游脚本更新"
		echo -e "$green  sh \$jd checkjs_tg $white      #调用checkjs监控tg频道变量（需要docker容器）"
		echo ""
		echo " 脚本用法请到github查看说明"
		echo "-------------------------------------------"
		echo -e "$green 执行脚本安装与检测，请稍等$white" && sleep 5
		#检测网络环境
		wget -t 1 -T 20 https://raw.githubusercontent.com/xdhgsq/xdh/main/README.md -O /tmp/test_README.md
		if [ $? -eq 0 ];then
			echo -e "$green 网络正常$white"
		else
			echo -e "$red 网络连接异常，无法ping通github.com，休息5分钟插件再继续尝试下载脚本$white"
			echo -e "$green 如果5分钟过去还是这样，你可以强制代理github.com ，或者采用底下代码手动安装，看看什么问题 $white"
			echo -e "$green /etc/init.d/jd_openwrt_script stop $white"
			echo -e "$green /etc/init.d/jd_openwrt_script start $white"
			sleep 5m
			start
		fi

		#创建主文件
		if [ -e $dir_file ];then
			echo -e "$green 主文件夹创建完成$white"
		else
			mkdir  $dir_file
		fi

		if [ -e $dir_file/script_config ];then
			echo -e "$green script_config创建完成$white"
		else
			mkdir  $dir_file/script_config
		fi

		#wskey转换
		if [ -e $dir_file/script_config/wskey ];then
			echo -e "$green script_config/wskey已存在$white"
			sh $dir_file/script_config/wskey/wskey.sh if_system
		else
			git clone https://github.com/xdhgsq/wskey_convert.git $dir_file/script_config/wskey
			chmod 755 $dir_file/script_config/wskey/wskey.sh
			sh $dir_file/script_config/wskey/wskey.sh if_system
		fi

		#checkjs(用于检测上游仓库更新和监控tg变量)
		if [ -e $dir_file/Checkjs ];then
			echo -e "$green script_config/wskey已存在$white"
			sh $dir_file/Checkjs/checkjs.sh system_variable
		else
			git clone https://github.com/xdhgsq/Checkjs.git $dir_file/Checkjs
			chmod 755 $dir_file/Checkjs/checkjs.sh
			sh $dir_file/Checkjs/checkjs.sh system_variable
		fi

		#开始下载脚本
		if [ -e $dir_file/JD_Script ];then
			echo -e "$green $dir_file/JD_Script已存在$white"
		else
			git clone -b main https://github.com/xdhgsq/xdh.git $dir_file/JD_Script && Detect
			chmod 755 $dir_file/JD_Script/jd.sh
			sh $dir_file/JD_Script/jd.sh update
		fi

		#全局变量生效
		source /etc/profile

		#检测npm依赖(安装时间太久，放到最后)
		npm_install

	else
		echo "检测到环境已经搭建完成，关闭安装服务"
	fi
}

npm_install() {
	npm_if=$(cat $dir_file/npm_install.log | grep "安装完成" |wc -l)
	if [ $npm_if = "1" ];then
		echo -e "$green npm 安装完成$white"
	else
		sh $dir_file/JD_Script/jd.sh npm_install
		echo  "npm 安装完成" > $dir_file/npm_install.log
	fi
}

Detect() {
	if [ $? -eq 0 ]; then
		echo  ""
	else
		echo -e "$red 代码运行失败重新执行$white"
		start
	fi
}


stop() {
	clear
	echo "------------------------------------------"
	echo -e "$yellow 用于删除jd_openwrt_script$white"
	echo "------------------------------------------"

	echo -e "请先保存$green$dir_file/script_config$white，这个也会删除，这个是cookie和其他文件"
	echo ""
	seconds_left=15
	while [ ${seconds_left} -gt 0 ]; do
		echo -n "  ${seconds_left}秒以后开始删除,不清楚的现在crtl+c退出"
		sleep 1
		seconds_left=$(($seconds_left - 1))
		echo -ne "\r"
	done
		echo -e "$green删除计划任务$white"
		sed -i '/JD_Script/d' /etc/crontabs/root >/dev/null 2>&1
		sleep 5

		echo -e "$green开始删除全局变量$white"
		sed -i '/JD_Script/d' /etc/profile >/dev/null 2>&1
		sed -i '/wskey/d' /etc/profile >/dev/null 2>&1
		sed -i '/checkjs/d' /etc/profile >/dev/null 2>&1
		sed -i '/Checkjs/d' /etc/profile >/dev/null 2>&1

		sleep 5

		echo -e "$green删除脚本目录$white"
		if [ -d $dir_file ];then
			rm -rf $dir_file
		fi
		sleep 5

		echo -e "$green删除.ssh目录$white"
		rm -rf /root/.ssh
		sleep 5

		echo ""
		echo "---------------------------------------------------------"
		echo "			删除完成，玩的开心"
		echo "---------------------------------------------------------"
		. /etc/profile

}


